mercenary = {  "name": "Mercenary",
                        "level": 1,
                        "xp": 0,
                        "next_level": 25,
                        "strength": 10,
                        "health": 200,
                        "maxHP": 200,
                        "armor": 20,
                        "damage": 100,
                        "reward": 300,
                        "pos_x": 5,
                        "pos_y": 5,
                        "icon": 'M',
                        "inventory": {}}

infantry_of_Troy = {  "name": "Soldier of Troy",
                "level": 1,
                "xp": 0,
                "next_level": 25,
                "strength": 10,
                "health": 500,
                "maxHP": 500,
                "armor": 50,
                "damage": 20,
                "reward": 500,
                # "pos_x": PLAYER_START_X,
                # "pos_y": PLAYER_START_Y,
                # "icon": PLAYER_ICON,
                "inventory": {}}

cavalry_of_Troy = {  "name": "Raider of Troy",
                "level": 1,
                "xp": 0,
                "next_level": 25,
                "strength": 10,
                "health": 700,
                "maxHP": 700,
                "armor": 50,
                "damage": 30,
                "reward": 700,
                #"pos_x": PLAYER_START_X,
                #"pos_y": PLAYER_START_Y,
                #"icon": PLAYER_ICON,
                "inventory": {}}
                    
enemy_hero = {  "name": "Hector",
                "type": 'boss',
                "level": 1,
                "xp": 0,
                "next_level": 25,
                "strength": 10,
                "health": 1000,
                "maxHP": 1000,
                "armor": 50,
                "damage": 100,
                "reward": 1000,
                "pos_x": 10,
                "pos_y": 10,
                "icon": 'B',
                "is_alive": True,
                "inventory": {}}